general:
    logging:
        level: INFO
    outdir: ./results

observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    filters:
        - filter_type: par_value
          value_param: Crab
          variable: TARGET_NAME

datasets:
    dataset-type: MapDataset
    stack-datasets: false
    offset-max: 2 deg
    geom:
        skydir: [83.63, 22.01]
        width: [5, 5]
        binsz: 0.02
        coordsys: CEL
        proj: TAN
        axes:
          - name: energy
            hi_bnd: 70
            lo_bnd: 0.1
            nbin: 24
            interp: log
            node_type: edges
            unit: TeV
    energy-axis-true:
        name: energy
        hi_bnd: 100
        lo_bnd: 0.05
        nbin: 72
        interp: log
        node_type: edges
        unit: TeV
