observations:
    datastore: $GAMMAPY_DATA/hess-dl3-dr1
    obs_cone:
        frame: {frame}
        lon: {ra}
        lat: {dec}
        radius: {search_radius}
    obs_time:
        start: {tstart}
        stop: {tstop}

datasets:
    type: 1d
    stack: false
    geom:
        axes:
            energy:
                min: 0.1 TeV
                max: 60 TeV
                nbins: 24
            energy_true:
                min: 0.08 TeV
                max: 100 TeV
                nbins: 48
    background:
        method: reflected
    on_region:
        frame: {frame}
        lon: {ra}
        lat: {dec}
        radius: {on_size}
    safe_mask:
        methods: ['bkg-peak', 'edisp-bias']
    containment_correction: true

fit:
    fit_range:
        min: 0.1 TeV
        max: 60 TeV

flux_points:
    energy:
        min: 0.1 TeV
        max: 60 TeV
        nbins: 36
    source: {tag}
