observations:
  datastore: $GAMMAPY_DATA/hess-dl3-dr1
  obs_cone:
    frame: icrs
    lon: {ra}
    lat: {dec}
    radius: 5 deg

datasets:
  type: 3d
  stack: true
  geom:
    wcs:
      skydir:
        frame: icrs
        lon: {ra}
        lat: {dec}
      binsize: 0.02 deg
      fov:
        width: 5 deg
        height: 5 deg
      binsize_irf: 0.2 deg
      margin_irf: 0.5 deg
    selection:
      offset_max: 2.5 deg
    axes:
      energy:
        min: 0.1 TeV
        max: 90 TeV
        nbins: 24
      energy_true:
        min: 0.1 TeV
        max: 100 TeV
        nbins: 72
  map_selection: ['counts', 'exposure', 'background', 'psf', 'edisp']


