components:
- name: {tag}
  type: SkyModel
  spatial:
    type: {spatial_model}
    frame: {frame}
    parameters:
    - name: lon_0
      value: {ra_value} # TODO: remove this, once units are uniformly handled in config files
      unit: deg
    - name: lat_0
      value: {dec_value}
      unit: deg
  spectral:
    type: PowerLawSpectralModel
    parameters:
    - name: amplitude
      value: 1.0e-11
      unit: cm-2 s-1 TeV-1
    - name: index
      value: 2.0
      unit: ''
    - name: reference
      value: {e_decorr_value}
      unit: TeV
      frozen: true
