observations:
    datastore: $CTADATA/index/gps/
    obs_cone:
      frame: galactic
      lon: {lon}
      lat: {lat}
      radius: {radius}

datasets:
    type: 3d
    stack: true
    geom:
        wcs:
            skydir:
              frame: galactic
              lon: {lon}
              lat: {lat}
            binsize: 0.02 deg
            fov:
              width: 2 deg
              height: 2 deg
        selection:
            offset_max: 4 deg
        axes:
            energy:
              min: {emin}
              max: {emax}
              nbins: {nbin}
    map_selection: ['counts', 'exposure', 'background', 'psf', 'edisp']


fit:
    fit_range:
        min: {emin}
        max: {emax}

flux_points:
    energy:
        min: {emin}
        max: {emax}
        nbins: {fp_nbin}
