general:
    logging:
        level: INFO
    outdir: .

observations:
    datastore: $CTADATA/index/gps/
    filters:
        - filter_type: sky_circle
          frame: galactic          #  or icrs
          lon: 111.734 deg
          lat: -2.129 deg
          radius: 2 deg
          border: 2 deg

datasets:
    dataset-type: MapDataset
    stack-datasets: true
    offset-max: 4 deg
    geom:
        skydir: [111.734, -2.129]
        width: [2, 2]
        binsz: 0.02
        coordsys: GAL
        proj: TAN
        axes:
          - name: energy
            hi_bnd: 50
            lo_bnd: 0.1
            nbin: 30
            interp: log
            node_type: edges
            unit: TeV

fit:
    fit_range:
        max: 50 TeV
        min: 0.1 TeV

flux-points:
    fp_binning:
        lo_bnd: 0.1
        hi_bnd: 50
        interp: log
        nbin: 10
        unit: TeV
