name: manual
on:
  workflow_dispatch:
jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GAMMAPY_DATA: /home/runner/work/gammapy-benchmarks/gammapy-benchmarks/gammapy-datasets
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: get env file
        run: curl -O https://raw.githubusercontent.com/gammapy/gammapy/master/environment-dev.yml
      - name: create and activate env
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: gammapy-dev
          environment-file: environment-dev.yml
          auto-update-conda: true
      - name: install gammapy
        run: |
          pip install git+https://github.com/gammapy/gammapy.git#egg=gammapy
          pip install psrecord
          conda info
          conda list
          gammapy info
      - name: download datasets
        run: gammapy download datasets
      - name: run benchmarks
        run: |
          cd benchmarks
          python make.py run-benchmark all
          cd results
          python track_evolution.py
      - name: run validations
        run: |
          cd validation
          python make.py run-validation all
          pytest -v
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Commit results from benchmarks and validations'
